apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ayam-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ayam-admin
subjects:
- kind: ServiceAccount
  name: ayam-admin
  namespace: ayam-jenkins
