apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:
      volumes:
      - name: jenkins-server-data-aws
        persistentVolumeClaim:
          claimName: aws-ebs-pvc
      containers:
      - name: jenkins
        image: 019273956931.dkr.ecr.eu-west-1.amazonaws.com/ayam-ecr-repo:jenkins-server
        volumeMounts:
        - name: jenkins-server-data-aws
          mountPath: /var/lib/jenkins
