apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
  labels:
    type: aws-ebs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-08737aa78523fef34
    fsType: xfs
