apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-pvc
    labels:
       type: aws-pvc
spec:
  accessModes:
    - ReadWriteOnce
resources:
  requests:
    storage: 3Gi
   selector:
    matchLabels:
      type: aws-pv
