---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage2
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume2
  labels:
    type: local
spec:
  storageClassName: local-storage2
  claimRef:
    name: jenkins-pv-claim2
    namespace: ayam-jenkins
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-192-168-83-142.eu-west-1.compute.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim2
  namespace: ayam-jenkins
spec:
  storageClassName: local-storage2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
