apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      volumes:
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: nginx-pvc
      containers:
        - name: polybot
          image: "019273956931.dkr.ecr.eu-west-1.amazonaws.com/ayam-ecr-repo:nginx"
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-pvc
          resources:
            limits:
              cpu: "1"
              memory: "100Mi"
            requests:
              cpu: "0.5"
              memory: "50Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - cat
                - /var/www/html/index.html
            initialDelaySeconds: 1
            periodSeconds: 5
