apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
      tier: backend
  template:
    metadata:
      labels:
        app: polybot
        tier: backend
    spec:
      volumes:
        - name: polybot-pvc
          persistentVolumeClaim:
            claimName: polybot-pvc
      containers:
        - name: polybot
          image: "019273956931.dkr.ecr.eu-west-1.amazonaws.com/ayam-ecr-repo:poly-bot-6"
          volumeMounts:
            - mountPath: /home/ec2-user/PolyBot/pvc-polybot
              name: polybot-pvc
          resources:
            limits:
              cpu: "1"
              memory: "100Mi"
            requests:
              cpu: "0.05"
              memory: "50Mi"
