apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: servicebus-scaledobject
  namespace: <your namespace> # Kubernetes Namespace name
spec:
  scaleTargetRef:
    name: <Deploy name> # Deployment Name to which you want to Autoscale
  triggers:
  - type: azure-servicebus
    Metadata:
      queueName: <Queue Name>
      topicName: <Topic Name>
      subscriptionName: <Subscription Name>
      messageCount: "1" # Event on which the autoscale triggered. 
    authenticationRef:
        name: azure-servicebus-trigger #TriggerAuthentication
