apiVersion: v1
kind: Secret
metadata:
 name: azure-servicebus-secret #Name of the Secret, needed in TriggerAuthentication
stringData:
 sbKey: RmcnsdhfnwiefNWDNxasknwoenfnocvoeioecvos= #Service Bus Connection String
