apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    apps: {{ include "nginx.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nginx.name" . }}
  template: 
    metadata:
      labels:
        apps: {{ include "nginx.name" . }}
    spec:
      containers:
          - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePULLpOLICY: {{ .Values.image.pullPolicy }}
          ports:
              - name: nginx
                containersPort: 8080
                protocol: TCP
