apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: servicebus-scaledobject
  namespace: demo-app # Kubernetes Namespace name
spec:
  scaleTargetRef:
    name: polybot # Deployment Name to which you want to Autoscale
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: functions-sbtopic
      subscriptionName: sbtopic-sub1
      messageCount: "1" # Event on which the autoscale triggered.
    authenticationRef:
      name: azure-servicebus-trigger #TriggerAuthentication
