apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-trigger
spec:
  secretTargetRef:
    - parameter: connection
      name: azure-servicebus-secret
      key: updatedKey
