apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  namespace: polybot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: polybot:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
        - mountPath: /app/secrets
          name: secret-volume
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
            secretName: myregistrykey
        persistentVolumeClaim:
          claimName: nginx-pvc

